### ISSUE TITLE
Setup Error / Unexpected end of JSON input

### ISSUE THREAD

**Issue by nnnnathann** [metral/corekube#15]
Hello all,

I'm having some trouble deploying out to Rackspace (RackConnect v3) using the rackconnect-v3 yaml.

Here is the error I am getting from the overlord after deployment:

```
2015/05/22 17:08:44 ------------------------------------------------
2015/05/22 17:08:44 Current # of machines discovered: (4)
2015/05/22 17:08:44 ------------------------------------------------
2015/05/22 17:08:44 Found machine:
2015/05/22 17:08:44 -- ID: 3c59a19de5a848ffb7969d22e02f01b9
2015/05/22 17:08:44 -- IP: 172.19.1.10
2015/05/22 17:08:44 -- Metadata: (kubernetes_role => master)
2015/05/22 17:08:44 Created all unit files for: 3c59a19de5a848ffb7969d22e02f01b9
2015/05/22 17:08:44 ------------------------------------------------
2015/05/22 17:08:44 Found machine:
2015/05/22 17:08:44 -- ID: 6136462ad4e547608456f2ba20cb310e
2015/05/22 17:08:44 -- IP: 172.19.1.9
2015/05/22 17:08:44 -- Metadata: (kubernetes_role => minion)
2015/05/22 17:08:44 Created all unit files for: 6136462ad4e547608456f2ba20cb310e
2015/05/22 17:08:44 ------------------------------------------------
2015/05/22 17:08:44 Found machine:
2015/05/22 17:08:44 -- ID: c047453d369e4db7a8054a70deabc726
2015/05/22 17:08:44 -- IP: 172.19.1.7
2015/05/22 17:08:44 -- Metadata: (kubernetes_role => minion)
2015/05/22 17:08:44 Created all unit files for: c047453d369e4db7a8054a70deabc726
2015/05/22 17:08:44 ------------------------------------------------
2015/05/22 17:08:44 Found machine:
2015/05/22 17:08:44 -- ID: 824f77d9d59145919b33ae7e61d15186
2015/05/22 17:08:44 -- IP: 172.19.1.8
2015/05/22 17:08:44 -- Metadata: (kubernetes_role => minion)
2015/05/22 17:08:44 Created all unit files for: 824f77d9d59145919b33ae7e61d15186
2015/05/22 17:08:46 [Error] in github.com/metral/overlord/lib.Main[/gopath/src/github.com/metral/overlord/lib/utils.go:52] unexpected end of JSON input
```

Any help would be appreciated!  Thanks for this repo.

**Comment by metral** [comment]
@cedbossneo is/was the maintainer for the rackconnect template. corekube has been updated quite a bit since the rackconnect template was last touched.

hoping @cedbossneo can chime in and possibly update it, if not, i can examine it

**Comment by nnnnathann** [comment]
FYI, I gave it another shot by just updating the commit hash for overlord in the rackconnect file, thinking maybe it was just a version mismatch issue.  That failed also for a different reason

```
May 22 17:42:13 kubernetes-master-0 systemd[1]: master-apiserver@a4aa28b6d3a340aea9182d5795c75626.service holdoff time over, scheduling restart.
May 22 17:42:13 kubernetes-master-0 systemd[1]: Stopping Kubernetes API Server...
May 22 17:42:13 kubernetes-master-0 systemd[1]: Starting Kubernetes API Server...
May 22 17:42:13 kubernetes-master-0 systemd[1]: Failed to load environment files: No such file or directory
```

Probably going to stop here for now and await response, thanks so much for the help!

**Comment by nnnnathann** [comment]
Also, I wouldn't mind diving in myself if you all have an idea of where to start?  I'm new to a lot of things but might be able to help out with a pointer in the right direction?

Again, thanks for the time and the effort to set up this repo!

**Comment by metral** [comment]
@nnnnathann your best bet is to take the corekube-rackconnect-v3.yaml (https://github.com/metral/corekube/blob/master/corekube-rackconnect-v3.yaml) and adapt it to model the corekube-cloudservers.yaml (https://github.com/metral/corekube/blob/master/corekube-cloudservers.yaml) as closely as possible. come to think of it, given that there are extra network interfaces on public cloud, the yaml file for rackconnect will probably resemble that of OnMetal (https://github.com/metral/corekube/blob/master/corekube-onmetal.yaml).

I'd start on that path and see how far it gets you. Unfortunately, I can't be of much help for RackConnect as I don't have an account to use in that environment but I can provide feedback & guidance if needed.

Please keep us posted

**Comment by cedbossneo** [comment]
Hi, sorry i wasnt available last week,

I will update the template tonight/tomorrow

Regards

**Comment by cedbossneo** [comment]
I've release a updated version of the heat file but i can't test it right now, if you want to try :
https://github.com/cedbossneo/corekube/tree/heat_file_rc3

**Comment by nnnnathann** [comment]
It appears to have worked!

Thank you both.

**Comment by metral** [comment]
closing due to the issue being resolved

**Comment by nnnnathann** [comment]
No big deal, but I think this is not resolved technically until the aforementioned rackconnect heat file is merged?

https://github.com/cedbossneo/corekube/blob/update-heat-file/corekube-rackconnect-v3.yaml

Thanks everyone

**Comment by metral** [comment]
@nnnnathann it was merged yesterday: https://github.com/metral/corekube/pull/17

**Comment by nnnnathann** [comment]
ha, nope, I'll see myself out.  thanks again

![homer](http://media0.giphy.com/media/4pMX5rJ4PYAEM/giphy.gif)

**Comment by metral** [comment]
Haha no worries. Please let us know if you encounter any other issues with
Corekube

On Friday, May 29, 2015, Nathan Bleigh <notifications@github.com> wrote:

> ha, nope, I'll see myself out. thanks again
>
> [image: homer]
> <https://camo.githubusercontent.com/cc27c7512bc3fbd407e67611527c985a2adc0131/687474703a2f2f6d65646961302e67697068792e636f6d2f6d656469612f34704d5835724a34505941454d2f67697068792e676966>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/metral/corekube/issues/15#issuecomment-106834756>.
>


-- 
-Mike Metral
